---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: aws-secret-access-key
  namespace: rhdp-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: aws-secret-access-key
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: aws-secret-access-key
