---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: jetstack
  namespace: cert-manager
spec:
  pathname: https://charts.jetstack.io
  type: HelmRepo
