---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
  labels:
    app: cert-manager
  name: cert-manager
  namespace: cert-manager
spec:
  channel: cert-manager/jetstack
  name: cert-manager
  packageOverrides:
  - packageName: cert-manager
    packageAlias: cert-manager
    packageOverrides:
    - path: spec
      value:
        installCRDs: true
        extraArgs: ['--dns01-recursive-nameservers=1.1.1.1:53','--dns01-recursive-nameservers-only']
  packageFilter:
    version: "v1.10.2"
  placement:
    placementRef:
      kind: PlacementRule
      name: cert-manager
