---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: hcp-cluster-config
  namespace: rhdp-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: hcp-cluster-config
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: PolicySet
  name: hcp-cluster-config
