---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: redhat-cert-manager-installed
  namespace: rhdp-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: redhat-cert-manager-installed
      spec:
        remediationAction: enforce
        pruneObjectBehavior: DeleteIfCreated
        severity: medium
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: cert-manager-operator
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: openshift-cert-manager-operator
              namespace: cert-manager-operator
            spec:
              channel: stable
              installPlanApproval: Automatic
              name: openshift-cert-manager-operator
              source: redhat-operators
              sourceNamespace: openshift-marketplace
