---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-gitops-installed
  namespace: rhdp-policies
spec:
  clusterSelector:
    matchLabels:
      vendor: OpenShift
      type: sandbox
