---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-gitops-installed
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1beta1
      kind: OperatorPolicy
      metadata:
        name: openshift-gitops-installed
      spec:
        remediationAction: enforce
        severity: medium
        complianceType: musthave
        subscription:
          channel: gitops-1.13
          installPlanApproval: Automatic
          name: openshift-gitops-operator
          namespace: openshift-operators
          source: redhat-operators
          sourceNamespace: openshift-marketplace
        upgradeApproval: Automatic
        removalBehavior:
          operatorGroups: DeleteIfUnused
          subscriptions: Delete
          clusterServiceVersions: Delete
          installPlans: Delete
          customResourceDefinitions: Delete
