---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hcp-policies

resources:
- hcp-policyset
- admin-authorization
- aws-secret-access-key
- kubeadmin-absent
- openshift-gitops-installed
- openshift-pipelines-installed
- openshift-serverless-installed
- redhat-cert-manager-installed
