---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hcp-policies

resources:
- hcp-policyset
- aws-secret-access-key
- redhat-cert-manager-installed
- openshift-gitops-installed
#- kubeadmin-absent
#- openshift-pipelines-installed
#- openshift-serverless-installed
# - admin-authorization
